import 'react-quill-new/dist/quill.snow.css';
import "~/styles/globals.css";
import { type Metadata } from "next";
import { Providers } from "~/app/provider";
import { Header } from "~/components/header/header";
import { Center } from "~/components/common/container-center";
import { LandingSideBar } from "~/components/landing/side-bar";
import { Footer } from "~/components/footer/footer";
import { Inter } from 'next/font/google'
import { Space_Grotesk } from 'next/font/google'
import { JetBrains_Mono } from 'next/font/google'
import { Toaster } from "~/components/ui/sonner";

export const textFont = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-text',
})

export const headingFont = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
})

export const codeFont = JetBrains_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-code',
})

export const metadata: Metadata = {
  title: "ByteVerse",
  description: "Generated by create-t3-app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${textFont.variable} ${headingFont.variable} ${codeFont.variable}`}>
      <body className="">
        <Providers>
          <Header />
          <Center className="grid grid-cols-12">
            <LandingSideBar />
            <main className="col-span-10">{children}</main>
          </Center>
          <Footer/>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
