
import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Providers } from "~/app/tags/provider";
import { Header } from "~/components/header/header";
import { Center } from "~/components/common/container-center";
import { LandingSideBar } from "~/components/landing/side-bar";
import { Footer } from "~/components/footer/footer";

export const metadata: Metadata = {
  title: "ByteVerse",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="">
        <Providers>
          <Header />
          <Center className="grid grid-cols-12">
            <LandingSideBar />
            <main className="col-span-10 ring-blue-950">{children}</main>
          </Center>
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
